mec_uploads_cache/rails_mec/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :posts
  resources :home
  resources :login

  devise_scope :user do
    get 'user/:id', to: 'users/registrations#detail'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
  end
end

mec_uploads_cache/rails_mec/app/controllers/login_controller.rb
# frozen_string_literal: true

class LoginController < ApplicationController
  def index; end

  def show
    @user = User.find_by(id: params[:id])
    home_path(params[:id]) if @user.client_id.present? && @user.access_token.present?
  end

  def update
    user = User.find_by(id: params[:id])
    user_param = params[:user]
    user.client_id = user_param[:client_id] if user_param[:client_id].present?
    user.client_secret = user_param[:client_secret] if user_param[:client_secret].present?
    if user_param[:access_token].present?
      @authenticator = DropboxApi::Authenticator.new(user.client_id, user.client_secret)
      @access_token = @authenticator.auth_code.get_token(user_param[:access_token])
      user.access_token = @access_token.token
      user.refresh_token = @access_token.refresh_token
      user.expires_in = (Time.zone.now + @access_token.expires_in).to_s
    end
    user.save!
  end
end

mec_uploads_cache/rails_mec/app/views/login/index.html.erb
<h2>Home</h2>

<%= link_to "アプリを作成してAppkeyを取得してください", "https://www.dropbox.com/developers/apps"%>

<%# <%= link_to "codeを取得してください", kobito_path, user_id: @user.id, user_name: @user.name %> %>

mec_uploads_cache/rails_mec/app/views/login/show.html.erb
<h2>Home</h2>
<%= link_to "アプリを作成してAppkeyを取得してください", "https://www.dropbox.com/developers/apps"%>
<%= form_for(@user, url: login_path, method: :patch) do |f| %>
  <%= f.text_field  :client_id %>
  <%= f.text_field  :client_secret%>
  <%= f.submit "appKeyを保存" %>
<% end %>
<%= link_to "codeを取得してください", "https://www.dropbox.com/oauth2/authorize/?client_id=#{@user.client_id}&response_type=code&token_access_type=offline"%>
<%= form_for(@user, url: login_path, method: :patch) do |f| %>
  <%= f.text_field  :access_token %>
  <%= f.submit "access_tokenを保存" %>
<% end %>

mec_uploads_cache/rails_mec/app/views/login/update.html.erb
<h2>update 完了</h2>
<%= link_to "ホームに戻る", login_path %>